# Table of Contents
0. [Importing PyTorch](#importing-pytorch)


1. [Introduction](#introduction)
* 1.1 [Scalar](#scalar)

* 1.2 [Vector](#vector)
* 1.3 [Matrix](#matrix)
* 1.4 [Tensor](#tensor)
* 1.5 [Random Tensors](#random-tensors)
* 1.6 [Zeros and Ones](#zeros-and-ones)
* 1.7 [Creating a range and tensor-like](#creating-a-range-and-tensor-like)
* 1.8 [Tensor DataType](#tensor-datatypes)
* 1.9 [Getting information from tensors](#getting-information-from-tensors)

2. [Manipulating Tensors](#manipulating-tensors)
* 2.1 [Basic Operations](#basic-operations)

* 2.2 [Matrix Multiplication](#matrix-multiplication) 
* 2.3 [Shape Errors](#shape-errors)
* 2.4 [Aggregation](#aggregation)
* 2.5 [Positional Aggregation](#positional-aggregation)
* 2.6 [Changing Tensor Datatype](#changing-tensor-datatype)
* 2.7 [Reshaping, Stacking, Squeezing, Unsqueezing](#reshaping-stacking-squeezing-unsqueezing)
* 2.8 [Indexing](#indexing)

3. [PyTorch tensors & Numpy](#pytorch-tensors--numpy)

4. [Accelerated PyTorch training on Mac](#accelerated-pytorch-training-on-mac)
* 4.1 [Installing](#installing)

* 4.2 [Verify](#verify)
* 4.3 [Loading the data](#loading-the-data)

In [2]:
import warnings
warnings.filterwarnings("ignore")

# Importing PyTorch

In [3]:
import torch

In [4]:
torch.__version__

'2.0.0.dev20230212'

# Introduction

## Scalar

##### For a tensor with just scalar figures, they are 0 dimensional tensors.

In [5]:
# Scalar - 0 dimension tensor
scalar = torch.tensor(6)
scalar

tensor(6)

##### We can check the number of dimensions with the function ndim.

In [6]:
# Checking for number of dimensions
scalar.ndim

0

##### To turn torch.Tensor to a Python integer, we can use the item() method.

In [7]:
scalar.item()

6

## Vector

##### A vector is a single dimensional tensor but can contain many numbers.

In [8]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

##### The trick to obtaining the number of dimensions from tensors is by counting the number of square brackets on the outside ([).

In [10]:
# Check shape of vector
vector.shape

torch.Size([2])

##### In a nutshell, this is a one dimensional vector with 2 elements inside.

## Matrix

In [11]:
# Matrix
matrix = torch.tensor([[7, 8],
                        [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
matrix.ndim

2

##### With two square brackets at the start, this is a 2 dimensional matrix.

In [13]:
matrix.shape

torch.Size([2, 2])

## Tensor

In [14]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
[4, 5, 6],
[7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

##### Tensors are the most powerful with the most power - able to represent almost anything.

In [15]:
tensor.ndim

3

##### With 3 brackets, there are 3 dimensions.

In [16]:
tensor.shape

torch.Size([1, 3, 3])

##### For the dimensions, the dimensions go outer to inner.
##### That means, there are 1 dimension of 3 by 3.
##### The easy way to understand this is that the left most dimension would be the outer most dimension and the right most dimension would be the inner most dimension.

## Random Tensors

##### In machine learning, these tensors are very rarely manipulated or created by the user. 
##### In most cases, the tensors initially are randomized and through various algorithms such as different forms of gradient descent and back propagation, the values would be adjusted.
##### So it is important to be able to create random tensors.

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.7031, 0.6386, 0.5286, 0.9939],
         [0.7311, 0.1855, 0.8084, 0.0263],
         [0.3450, 0.6988, 0.2904, 0.7749]]),
 torch.float32)

##### The size of the random tensor can be easily manipulated by the parameter

In [18]:
# Creating a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

##### Sometimes, it's important just to fill the tensors with zeros and ones.
##### Especially useful when there is masking to be performed, especially for CNNs and image processing tasks.

In [19]:
# Create a tesnor of all zeros
zeros = torch.zeros(size = (3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

##### The same can be done with torch.ones() instead.

In [20]:
# Create a tensor of all ones 
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## Creating a range and tensor-like

##### There are ways to make it easy for the user to create ranges for tensors.

In [21]:
# We can use torch.range(start, end, step)
# torch.range will be deprecated
zero_to_ten_deprecated = torch.range(0, 10)

# Creatae a range of values 0 to 10
zero_to_ten = torch.arange(start = 0, end = 10, step = 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### There is also a method to create a tensor with the same shape as another tensor.

In [22]:
# We can use the torch.zeros_like(input) or torch.ones_like(input)
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have the same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

##### There are many different data types available for PyTorch.
##### Some are better for CPU and some are better for GPU.
##### Generally, the default is **torch.float32**.
##### This is the 32-bit floating point.
##### The greater the number of bits for floating points, the greater the precision it can represent.
##### However, greater number of bits sacrifices memory for precision since the computer would need to allocate more memory space for more number of bits.

In [23]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None, # Defaults to None
                                device = None, 
                                requires_grad=False # If true, operations performed on the tensor is recorded which is required for backpropagation
                                )
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

##### PyTorch prefers calculations between same datatypes and requires that the values being operated be on the same device, either the CPU or GPU

In [24]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype = torch.float16)
float_16_tensor.dtype

torch.float16

## Getting information from tensors

##### Some of the important information one can extract from a tensor is 
##### 1) shape of tensor
##### 2) dtype of elements in the tensor
##### 3) device that the tensor is on

In [25]:
# Create a tensor
some_tensor = torch.rand(3,4) # Random tensor with shape (3,4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.3326, 0.1929, 0.5198, 0.3456],
        [0.8108, 0.2305, 0.2154, 0.6817],
        [0.8683, 0.4872, 0.8989, 0.1642]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


##### With errors when using PyTorch, most of them can be attributed to any of the three reasons above.

# Manipulating Tensors

##### It is important to know how to manipulate tensors.
##### In Deep Learning, data (images, text, sound, protein structures, time series) are to be represented as tensors.
##### Operations are then performed on these tensors to arrive at the most optimal values that successfully performs the intended task, be it image recognition, sentence generation, language translation and so on.

## Basic Operations

##### The most basic operations are addition, subtraction and multiplication.

In [26]:
# Addition
tensor = torch.tensor([1, 2, 3]) # Shape would just be [3]
tensor + 10

tensor([11, 12, 13])

In [27]:
tensor * 10

tensor([10, 20, 30])

##### As you can see, tensors are different from python lists.
##### Addition and multiplication of the tensors themselves would act on every element of the tensor.

In [28]:
tensor = tensor - 10 # Same as tensor -= 10
tensor

tensor([-9, -8, -7])

In [29]:
tensor += 10 
tensor

tensor([1, 2, 3])

##### These operations are pretty simple.
##### There are some convenient functions to help with these operations such as mul (multiplication) and add (addition).

In [30]:
torch.mul(tensor, 10) # This wouldn't change the tensor itself

tensor([10, 20, 30])

In [31]:
torch.add(tensor, 10)

tensor([11, 12, 13])

## Matrix Multiplication

##### Now, at least in deep learning, this is the most important cocnept and function you would need to know.
##### In Neural Networks, calculations are carried out in matrix multiplications instead of individual values being tracked, calculated and accounted for.
##### Matrix Multiplication can be carried out using the torch.matmul() function.
##### Now, if we remember high school matrix multiplication, the one rule we need to keep in mind is that the inner dimensions must match.
##### Eg.) (3, 2) @ (3, 2) won't work
##### Eg.) (3, 2) @ (2, 3) will work
##### Also, the resulting matrix will have the dimensions of the outer dimensions of the input matrices.
##### Eg.) (2, 3) @ (3, 2) will yield (2, 2)

##### Let's take a look at the element-wise multiplication and matrix multiplication.

In [32]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [33]:
# Element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [34]:
# Matrix multiplication (dot-product)
torch.matmul(tensor, tensor)

tensor(14)

##### The inner workings of matmul is pretty intuitive and can be performed using a simple for looop.

In [35]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 422 µs, sys: 313 µs, total: 735 µs
Wall time: 469 µs


tensor(14)

In [36]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 123 µs, sys: 20 µs, total: 143 µs
Wall time: 126 µs


tensor(14)

##### This should make it obvious why we stick to using torch.matmul ^-^

## Shape Errors

##### This error deserves a section of its own and personally, it is my own hell too. 
##### Taking note of shapes of multiplication may seem simple now but when utilizing DNNs, it is way too easy to lose track of multiplication within the network and result in numerous errors.

In [37]:
# Shapes need to be in the right way 
Tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype = torch.float32)
Tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype = torch.float32)

# Both tensors are of the shape (3, 2)
torch.matmul(Tensor_A, Tensor_B) # This is definitely going to give us an error!

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

##### This is probably the most frequent error you would see throughout your Deep Learning journey.
##### One way to make the inner dimensions match is to transpose one of the matrices. 
##### **Transposing** is switching the dimensions of a tensor/matrix.
##### *torch.tranpose(input, dim0, dim1)* can be used where input is the desired tensor to be transposed and dim0 and dim1 are the dimensions to be swapped.
##### *tensor.T* can also be used for a simple transposition.

In [38]:
print(Tensor_A)
print(Tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [39]:
# tensor.T
print(Tensor_A)
print(Tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [40]:
torch.matmul(Tensor_A, Tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

##### Nice! 
##### We can see that it works as intended now.
##### If you want to get serious with Neural Networks, I recommend getting awfully familiar with matrix multiplications.
##### In the feed-forward layer, the inputs ($x$) and the weights matrix ($A$)  gets matmul-ed.

$$\LARGE y = x \cdot A^T + b $$

##### I highly recommend you to go read up on dot product to learn more about matrix multiplication (matmul).
##### Matmul is essentially the dot product after all.

##### For now, let's play around with that equation above.

In [41]:
torch.manual_seed(42) # Random Seed value to allow us to easily reproduce results later on
linear = torch.nn.Linear(in_features = 2, # Input dimension
                         out_features = 6) # Output dimension

x = Tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:

tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


##### As we can see, in went 2 features and out came 6 features, just as we expected.
##### The number 3 can be interpreted as the number of instances of number of intput data we have.

## Aggregation

##### There are several ways to manipulate tensors.
##### These methods help us to obtain important information from tensors.

In [42]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

##### Now let's see some aggregation in action.

In [43]:
print(f"Maximum: {x.max()}")
print(f"Minimum: {x.min()}")
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Maximum: 90
Minimum: 0
Mean: 45.0
Sum: 450


##### The max, min, sum functions are pretty intuitive.
##### However, the mean function may not be that intuitive.
##### We have to remember that for the .mean() function, the tensor needs to be in a specific datatype to work, which in this case is a torch.float32 datatype.

## Positional Aggregation

##### We can also find the **index** within the tensor where the max or min occurs with torch.argmax() and torch.argmin() respectively.
##### This is helpful when we just want the position of the values we are interested in. 

In [44]:
print(f"Index where max value occurs: {x.argmax()}")
print(f"Index where min value occurs: {x.argmin()}")

Index where max value occurs: 9
Index where min value occurs: 0


## Changing tensor datatype

##### Apart from the tensors' shapes being different and leading to an error, the datatypes of tensor can also lead to errors.
##### If the tensors used in calculations have different datatypes, the user needs to take action in order to transform them into the same datatypes.
##### This can be easily done by using the torch.Tensor.type() function.

In [45]:
# Create a tensor and check its datatype 
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [46]:
# Change the tensor to a torch.float16 datatype
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [47]:
# Change the tensor to a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

##### These manipulations are important when you want to unite all the datatypes into a single form. 
##### Additionally, the smaller bits datatypes are mostly used when storage and computation speeds are prioritised. 
##### On the contrary, the larger bits datatypes are mostly used when accuracy of the model is prioritised.

## Reshaping, Stacking, Squeezing, Unsqueezing

##### Often, we would want to reshape/change the dimensions of our tensors without actually changing the values inside them.
##### Some of the methods are as listed
* torch.reshape()
* torch.Tensor.view()
* torch.stack()
* torch.squeeze()
* torch.unsqueeze()
* torch.permute()

##### These methods are very useful when it comes to Deep Learning operations. 
##### Most of the time, with matrix multiplication, we would need to be able to manipulate matrices into the shapes that we want.

In [48]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [49]:
# Adding an extra dimension
x_reshaped = x.reshape(1, 7) # Would reshape to this shape
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

##### We can also perform seemingly the same operation with the function torch.view().

In [50]:
z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

##### Now you might be asking what is the difference between view and reshape function.
##### You can understand view by thinking of it as a view of the original tensor.
##### This means when you alter or change the viewed tensor, z, the original tensor, x, would change too.

In [51]:
# Altering the viewed tensor, z
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

##### We could also stack tensors on top of each other using torch.stack().

In [52]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0) # Stack along the columns
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [53]:
x_stacked = torch.stack([x, x, x, x], dim = 1) # Stack along the rows
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

##### Taking note of how the dim parameter affects the results would also help when trying to manipulate the matrix to your liking.

##### Now, how about torch.squeeze()?
##### An easy way to remember this is to just think of squeezing the massive matrix into a single dimension by removing extra dimensions.

In [54]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


##### We can also perform the reverse operations using the torch.unsqueeze() to add a dimension value of 1 at a specific index.

In [55]:
print(f"Previous tensor: {x_squeezed}")
print(f"Prevous shape: {x_squeezed.shape}")

# Adding a dimension value of 1 at the 0th index
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

# Adding a dimension value of 1 at the 1st index
x_unsqueezed = x_squeezed.unsqueeze(dim = 1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Prevous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.]])
New shape: torch.Size([7, 1])


##### torch.permute(input, dims) helps us to rearrange the order of dimension axes.
##### This method will return us a view of the input tensor.
##### This means the same thing: changing the values of the view tensor would alter the original too.

In [56]:
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2, 0, 1) # will shift axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing

##### As someone who plays around with data, indexing with PyTorch should be easy.
##### It is basically the same as indexing on Python lists or Numpy arrays.

In [57]:
x = torch.arange(1,10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

##### When indexing tensors, the order goes as such: outer dimensions -> inner dimensions

In [58]:
print(f"First square bracket: \n{x[0]}\n")
print(f"Second sqaure bracket: \n{x[0][0]}\n")
print(f"Third square bracket: \n{x[0][0][0]}\n")

First square bracket: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Second sqaure bracket: 
tensor([1, 2, 3])

Third square bracket: 
1



##### : can also be used to specify "all values in this dimension"

In [59]:
# Will show us all the values in the 0th dimension
x[:, 0]

tensor([[1, 2, 3]])

In [60]:
# Will show all the values in the 0th and 1st dimension but only the 1st index in the last dimension
x[:, :, 1]

tensor([[2, 5, 8]])

# PyTorch tensors & Numpy

##### In the field of data science, Numpy is used widely as a tool to store, express, operate on numerical figures and large data. 
##### Thus, PyTorch and Numpy have functionalities to interact smoothly between them.

##### The two methods we need to know is: 
1. torch.from_numpy(ndarray) 


2. torch.Tensor.numpy()

##### The first is to change a numpy array to a PyTorch tensor while keeping the values.
##### The second is to change a tensor to a numpy array.

In [61]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

##### Something to keep in mind is that numpy initilizes the datatypes of the elements in the array as float64.
##### However, elements in tensors are usually expressed as float32 and calculations are done with the float32 datatypes.
##### Therefore, it is useful to remember, that when transforming from numpy array to a tensor, to change the datatype from float64 to float32 using .type(torch.float32).

In [62]:
tensor = torch.from_numpy(array).type(torch.float32)
tensor, tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

# Accelerated PyTorch training on Mac

##### With Deep Learning in general, the tasks require an immense amount of computation power. 
##### CPUs are capable of carrying out matrix multiplication, back propagation, calculus and much more.
##### However, CPUs are not optimized for these operations and GPUs turn out to be a way better option for these operations.
##### However, as we all know, Macbooks do not carry a Nvidia GPU within its device.
##### For PC users, CUDA is available and very easy to use. 
##### Since I am a Mac user, I will endeavour to explain how to use the accelerated PyTorch training using the **Metal Performance Shaders (MPS) backend for GPU training accerlation

## Installing

##### To be able to utilize the MPS backend, we would need to install the Preview (Nightly) build of Pytorch.

In [63]:
# Anaconda
"""
conda install pytorch torchvision torchaudio -c pytorch-nightly
"""

# pip
"""
pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu
"""

'\npip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu\n'

## Verify

##### To verify everything is working properly, run the code below.

In [64]:
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")

tensor([1.], device='mps:0')


##### The output should show:
##### tensor([1.], device='mps:0')

## Loading the data

##### To load our tensors onto the MPS backend:

In [65]:
tensor = torch.tensor([1, 2, 3])

tensor_on_gpu = tensor.to(mps_device)
tensor_on_gpu

print(tensor.device)
print(tensor_on_gpu.device)

cpu
mps:0
